//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Scripts/Input/Controls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace FreeBlob.Input
{
    public partial class @Controls : IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @Controls()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""Controls"",
    ""maps"": [
        {
            ""name"": ""Avatar"",
            ""id"": ""91e40513-bef8-41b6-a30a-b9b88e23cbbe"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""PassThrough"",
                    ""id"": ""1546b459-b18f-4710-be8b-e24d4ee36717"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Look"",
                    ""type"": ""PassThrough"",
                    ""id"": ""d2895bb4-d719-4860-8d2f-286c07c730dd"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""3c4affe5-b44a-41f7-9aa9-3d289e936f9d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Sonar"",
                    ""type"": ""Button"",
                    ""id"": ""3736fa0b-6288-4586-a08e-a1e6363cae6b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Menu"",
                    ""type"": ""Button"",
                    ""id"": ""a43aab79-05e1-485a-aa62-edf3a7c5983f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Sprint"",
                    ""type"": ""Button"",
                    ""id"": ""424a111d-04be-43e4-97c2-6a03f5279259"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Special"",
                    ""type"": ""Button"",
                    ""id"": ""591b5f0a-2f50-4c08-bb0a-1eb5e922b9f4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""b60ab0f7-a6d5-47ff-8310-8879dc84f356"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4326afba-ed6f-4daa-87ec-1be95fcbcdfc"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bb89e800-3d3f-4490-a953-8fc70ef94fa8"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Sonar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""f2dd2c3c-1181-40ae-b589-b6d52e38787b"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""8fe5e344-86e3-49b9-b198-2845c8c461fe"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""0d6fcbbf-1832-4890-9baa-e84ff9875b6f"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""d81bc17c-757f-4e1c-9204-c13eab771a0d"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""c69a1c84-526b-4eba-b47a-b4ebb332b992"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""fec13e22-3f13-4762-84f1-ed1b09d3a2d7"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Menu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""047da930-590b-48d1-a49e-678f2d60fdbe"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Sprint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4717a9cb-b3f1-4684-b95e-4d8e0e5f70a5"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Special"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""UI"",
            ""id"": ""b10567cd-d336-45ab-a68f-240106ae4dc6"",
            ""actions"": [],
            ""bindings"": []
        }
    ],
    ""controlSchemes"": []
}");
            // Avatar
            m_Avatar = asset.FindActionMap("Avatar", throwIfNotFound: true);
            m_Avatar_Movement = m_Avatar.FindAction("Movement", throwIfNotFound: true);
            m_Avatar_Look = m_Avatar.FindAction("Look", throwIfNotFound: true);
            m_Avatar_Jump = m_Avatar.FindAction("Jump", throwIfNotFound: true);
            m_Avatar_Sonar = m_Avatar.FindAction("Sonar", throwIfNotFound: true);
            m_Avatar_Menu = m_Avatar.FindAction("Menu", throwIfNotFound: true);
            m_Avatar_Sprint = m_Avatar.FindAction("Sprint", throwIfNotFound: true);
            m_Avatar_Special = m_Avatar.FindAction("Special", throwIfNotFound: true);
            // UI
            m_UI = asset.FindActionMap("UI", throwIfNotFound: true);
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }
        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }
        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // Avatar
        private readonly InputActionMap m_Avatar;
        private IAvatarActions m_AvatarActionsCallbackInterface;
        private readonly InputAction m_Avatar_Movement;
        private readonly InputAction m_Avatar_Look;
        private readonly InputAction m_Avatar_Jump;
        private readonly InputAction m_Avatar_Sonar;
        private readonly InputAction m_Avatar_Menu;
        private readonly InputAction m_Avatar_Sprint;
        private readonly InputAction m_Avatar_Special;
        public struct AvatarActions
        {
            private @Controls m_Wrapper;
            public AvatarActions(@Controls wrapper) { m_Wrapper = wrapper; }
            public InputAction @Movement => m_Wrapper.m_Avatar_Movement;
            public InputAction @Look => m_Wrapper.m_Avatar_Look;
            public InputAction @Jump => m_Wrapper.m_Avatar_Jump;
            public InputAction @Sonar => m_Wrapper.m_Avatar_Sonar;
            public InputAction @Menu => m_Wrapper.m_Avatar_Menu;
            public InputAction @Sprint => m_Wrapper.m_Avatar_Sprint;
            public InputAction @Special => m_Wrapper.m_Avatar_Special;
            public InputActionMap Get() { return m_Wrapper.m_Avatar; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(AvatarActions set) { return set.Get(); }
            public void SetCallbacks(IAvatarActions instance)
            {
                if (m_Wrapper.m_AvatarActionsCallbackInterface != null)
                {
                    @Movement.started -= m_Wrapper.m_AvatarActionsCallbackInterface.OnMovement;
                    @Movement.performed -= m_Wrapper.m_AvatarActionsCallbackInterface.OnMovement;
                    @Movement.canceled -= m_Wrapper.m_AvatarActionsCallbackInterface.OnMovement;
                    @Look.started -= m_Wrapper.m_AvatarActionsCallbackInterface.OnLook;
                    @Look.performed -= m_Wrapper.m_AvatarActionsCallbackInterface.OnLook;
                    @Look.canceled -= m_Wrapper.m_AvatarActionsCallbackInterface.OnLook;
                    @Jump.started -= m_Wrapper.m_AvatarActionsCallbackInterface.OnJump;
                    @Jump.performed -= m_Wrapper.m_AvatarActionsCallbackInterface.OnJump;
                    @Jump.canceled -= m_Wrapper.m_AvatarActionsCallbackInterface.OnJump;
                    @Sonar.started -= m_Wrapper.m_AvatarActionsCallbackInterface.OnSonar;
                    @Sonar.performed -= m_Wrapper.m_AvatarActionsCallbackInterface.OnSonar;
                    @Sonar.canceled -= m_Wrapper.m_AvatarActionsCallbackInterface.OnSonar;
                    @Menu.started -= m_Wrapper.m_AvatarActionsCallbackInterface.OnMenu;
                    @Menu.performed -= m_Wrapper.m_AvatarActionsCallbackInterface.OnMenu;
                    @Menu.canceled -= m_Wrapper.m_AvatarActionsCallbackInterface.OnMenu;
                    @Sprint.started -= m_Wrapper.m_AvatarActionsCallbackInterface.OnSprint;
                    @Sprint.performed -= m_Wrapper.m_AvatarActionsCallbackInterface.OnSprint;
                    @Sprint.canceled -= m_Wrapper.m_AvatarActionsCallbackInterface.OnSprint;
                    @Special.started -= m_Wrapper.m_AvatarActionsCallbackInterface.OnSpecial;
                    @Special.performed -= m_Wrapper.m_AvatarActionsCallbackInterface.OnSpecial;
                    @Special.canceled -= m_Wrapper.m_AvatarActionsCallbackInterface.OnSpecial;
                }
                m_Wrapper.m_AvatarActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @Movement.started += instance.OnMovement;
                    @Movement.performed += instance.OnMovement;
                    @Movement.canceled += instance.OnMovement;
                    @Look.started += instance.OnLook;
                    @Look.performed += instance.OnLook;
                    @Look.canceled += instance.OnLook;
                    @Jump.started += instance.OnJump;
                    @Jump.performed += instance.OnJump;
                    @Jump.canceled += instance.OnJump;
                    @Sonar.started += instance.OnSonar;
                    @Sonar.performed += instance.OnSonar;
                    @Sonar.canceled += instance.OnSonar;
                    @Menu.started += instance.OnMenu;
                    @Menu.performed += instance.OnMenu;
                    @Menu.canceled += instance.OnMenu;
                    @Sprint.started += instance.OnSprint;
                    @Sprint.performed += instance.OnSprint;
                    @Sprint.canceled += instance.OnSprint;
                    @Special.started += instance.OnSpecial;
                    @Special.performed += instance.OnSpecial;
                    @Special.canceled += instance.OnSpecial;
                }
            }
        }
        public AvatarActions @Avatar => new AvatarActions(this);

        // UI
        private readonly InputActionMap m_UI;
        private IUIActions m_UIActionsCallbackInterface;
        public struct UIActions
        {
            private @Controls m_Wrapper;
            public UIActions(@Controls wrapper) { m_Wrapper = wrapper; }
            public InputActionMap Get() { return m_Wrapper.m_UI; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(UIActions set) { return set.Get(); }
            public void SetCallbacks(IUIActions instance)
            {
                if (m_Wrapper.m_UIActionsCallbackInterface != null)
                {
                }
                m_Wrapper.m_UIActionsCallbackInterface = instance;
                if (instance != null)
                {
                }
            }
        }
        public UIActions @UI => new UIActions(this);
        public interface IAvatarActions
        {
            void OnMovement(InputAction.CallbackContext context);
            void OnLook(InputAction.CallbackContext context);
            void OnJump(InputAction.CallbackContext context);
            void OnSonar(InputAction.CallbackContext context);
            void OnMenu(InputAction.CallbackContext context);
            void OnSprint(InputAction.CallbackContext context);
            void OnSpecial(InputAction.CallbackContext context);
        }
        public interface IUIActions
        {
        }
    }
}
